Pull request del Sprint1
infabeti/Equipo1-Aitor-Unai pull request #1
Opened 2021-01-27 11:13 UTC by AitorCalderonLo

2021-01-27 12:22 UTC, infacorchado commented
La aplicación tiene muy buena pinta y la parte de programación está bastante bien pero he visto algunas cosillas a corregir y también algunas sugerencias: 

- En las pantallas de tickets/facturas/pedidos faltaría mostrar el total de unidades por producto , el precio total por producto y el precio total del ticket e igualmente para las facturas. Además, la fecha de caducidad del producto nos interesa para controlar el stock pero yo no la mostraría en ticket/factura ya que es información que no es relevante. 

- El número de transacción es algo que debería mostrarse cada vez que abrimos la pantalla para crear un ticket/factura / pedido nuevo. Además, tanto en tickets como facturas y pedidos debe registrarse la fecha (actual) y el local de forma automática (en el primer sprint no es necesario manejar fechas pero tendrían que estar los campos en las 3 pantallas).

- Validaciones: veo que las habéis realizado (aunque no funcionan ya que si pongo por ejemplo una 1 en cantidad a la hora de añadir el producto siempre me pone 1 en vez de advertir al usuario), sería mas útil que si lo que tengo que insertar es un número poner un control numérico por ejemplo. 

- A la hora de finalizar el ticket/factura y pedido sería bueno validar los campos que son obligatorios por ejemplo: el numero de tickets, que haya seleccionado como mínimo un producto... etc 

- A la hora de seleccionar un producto en el panel de pedido hacéis referencia a una clase del modelo. La vista no tiene visibilidad del modelo (en ticket y factura lo habéis hecho bien). 

Animo que ya queda poco!

2021-01-27 15:31 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/Controlador.java
> +	public static String getFechaHoraSys() {
Este método no tiene que estar en el contralador

2021-01-27 15:34 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +	private Producto[] listaProductos = new Producto[256];
Esto debería de ir en el modelo. Aparte de eso, porque tiene la longitud 256?

2021-01-27 15:36 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +	private int punt = 0;
Mueve el indice junto a la lista productos al modelo

2021-01-27 15:37 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		punt++;
Llevadlo al modelo junto el resto de las cosas

2021-01-27 15:38 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +	private String[] listaProductos;
No puedes tener un lista productos en cada panel. Crea uno en el modelo, y, si quieres puedes inicializarlo en el momento que te interese de la navegación.

2021-01-27 15:39 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +	private String[] listaProductos;
No te hace falta esta variable

2021-01-27 15:39 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPrincipal.java
> +
Borralo

2021-01-27 15:41 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +	private Producto[] listaProductos = new Producto[256];
Declara uno solo y lo inicializas según te convenga en base a la navegación.

2021-01-27 15:41 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +	private int punt = 0;
+1

2021-01-27 15:41 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +		punt++;
Reutiliza el método que vas a crear en el modelo

2021-01-27 15:42 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +		return numTransaccion;
this.

2021-01-27 15:42 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +		return fecha;
+1

2021-01-27 15:42 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +		return local;
+1

2021-01-27 15:42 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +	public Actividad() {}
Borralo

2021-01-27 15:43 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Aprovisionamiento.java
> +public class Aprovisionamiento extends Actividad{
Vas a usar polimorfismo? Porque, entonces te puede hacer algún comentario más de mejora.

2021-01-27 15:43 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Conexion.java
> +			+ "serverTimezone=UTC";
Declararlo como static

2021-01-27 15:43 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Conexion.java
> +			+ "serverTimezone=UTC";
Los estáticos los ponemos en mayusculas

2021-01-27 15:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Factura.java
> +		return nif;
this.

2021-01-27 15:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Factura.java
> +		return nombre;
+1

2021-01-27 15:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Factura.java
> +		return apellido;
+1

2021-01-27 15:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/LineaPedido.java
> +		return cantidad;
+1

2021-01-27 15:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/LineaPedido.java
> +		return total;
+1

2021-01-27 15:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/LineaPedido.java
> +		return producto;
+1

2021-01-27 15:45 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/ListaActividades.java
> +	private Actividad[] listaActividades = new Actividad[256];
256????

2021-01-27 15:49 UTC, infabeti requested changes
Empezad corregiendo lo que os he puesto y despues os miro el resto.

2021-01-27 15:49 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/ListaActividades.java
> +	public boolean annadirActividad(Actividad act) {
Me gusta. Para que no tengas que poner el 256 crea un método que te aumente dinamicamente el tamaño del array cada vez que introduzcas un elemento.

2021-01-27 15:49 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/ListaProdTienda.java
> +		return ok;
El metodo de añadir, buscar y eliminar es igual en todas las clases. Crea uno generico y lo llamas desde el resto de clases

2021-01-27 21:40 UTC, Jose-Elorrieta requested changes
Está bastante bien, pero tenéis que hacer unos cuantos cambios.
Me parece que ha sido un despiste en el diagrama E-R, porque luego en el paso al modelo relacional lo habéis hecho bien, pero una de las cardinalidades para la relación contiene es incorrecta.
En cuanto al diseño lógico:
•	La relación realiza entre Local y Actividad es de tipo 1:N y no hay ningún motivo por el cual deba lugar a una nueva tabla. 
•	Recordad que las flechas parten de la clave ajena y llegan a la clave primaria, esto es, la punta de flecha se debe colocar donde está la clave primaria. Hay alguna flecha incorrecta en este sentido.
•	Al esquema relacional dadle un formato más legible sin cruces de flechas, por favor.
•	Sigo pensando que una tabla con un solo atributo, como Ticket, es algo extraño, pero cuando añadáis las comandas al diagrama, ya veréis si tiene sentido o no esto. 
•	En el esquema relacional hay una tabla que no está en 3FN. A ver si la detectáis y hacéis el paso a 3FN, por lo que da lugar a una nueva tabla.
En cuanto al diseño físico:
•	Usad el tipo char y no varchar cuando el campo de tipo alfanumérico es de longitud fija.
•	Usad el tipo que hemos estudiado para dominios finitos (pocos valores posibles).
•	Este es un error grave: en varias tablas falta especificar su clave primaria. Toda tabla requiere una clave primaria.
Haced estos cambios que he solicitado, por favor, y avisadme cuando estén realizados.
¡Buen trabajo!

2021-01-30 11:55 UTC, Jose-Elorrieta requested changes
De acuerdo. Solo os falta un detalle, que es pasar la tabla Factura a 3FN. Ya veréis que es muy fácil.

2021-01-31 21:09 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/ListaProdTienda.java
> +		return ok;
He eliminado esas clases para en su lugar utilizar ArrayList y así tener una implementación más limpia de esas listas, es correcto o debería hacerlo de otra manera?

2021-02-01 08:24 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/Controlador.java
> +	public static String getFechaHoraSys() {
Arreglado

2021-02-01 08:25 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +	private Producto[] listaProductos = new Producto[256];
Arreglado

2021-02-01 08:25 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +	private int punt = 0;
Arreglado, están los dos en el modelo (se utilizaban para manejar la cantidad de productos que se habían escogido)

2021-02-01 08:25 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		punt++;
Arreglado

2021-02-01 08:26 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +	private String[] listaProductos;
Arreglado

2021-02-01 08:26 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPrincipal.java
> +
Borrado

2021-02-01 08:26 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +	private Producto[] listaProductos = new Producto[256];
Arreglado

2021-02-01 08:26 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +	private int punt = 0;
Arreglado

2021-02-01 08:26 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +		punt++;
Arreglado

2021-02-01 08:26 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +		return numTransaccion;
Arreglado

2021-02-01 08:26 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +		return fecha;
Arreglado

2021-02-01 08:27 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +		return local;
Arreglado

2021-02-01 08:27 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +	public Actividad() {}
Borrado

2021-02-01 08:28 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Aprovisionamiento.java
> +public class Aprovisionamiento extends Actividad{
Sí, el objetivo es utilizarlo para las distintas actividades. De actividad heredan aprovisionamiento, comandas y ticket y de ticket heredan pedidos y facturas ya que esos 3 hacen lo mismo

2021-02-01 08:29 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Aprovisionamiento.java
> +public class Aprovisionamiento extends Actividad{
Hacen lo mismo me refiero a que las 3 comparten varios atributos entre ellas, y ticket no tiene ninguno propio como pedido y factura por lo que heredan de este para hacerlo más sencillo

2021-02-01 08:30 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Conexion.java
> +			+ "serverTimezone=UTC";
Declarados como static final

2021-02-01 08:30 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Factura.java
> +		return nif;
Arreglado

2021-02-01 08:30 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Factura.java
> +		return nombre;
Arreglado

2021-02-01 08:30 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Factura.java
> +		return apellido;
Arreglado

2021-02-01 08:30 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/LineaPedido.java
> +		return cantidad;
Arreglado

2021-02-01 08:30 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/LineaPedido.java
> +		return total;
Arreglado

2021-02-01 08:30 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/LineaPedido.java
> +		return producto;
Arreglado

2021-02-01 08:30 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/ListaActividades.java
> +	private Actividad[] listaActividades = new Actividad[256];
Arreglado

2021-02-01 08:31 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/ListaActividades.java
> +	public boolean annadirActividad(Actividad act) {
He utilizado Arraylist para que se actualice el tamaño dinámicamente

2021-02-01 15:18 UTC, Jose-Elorrieta commented
El paso a 3FN está correctamente realizado si bien el nombre de la tabla Vendedor no es muy adecuado; sería más conveniente llamarla Comprador porque se entrega la factura a la persona que compra productos en el local. Por otro lado, no he conseguido ver los cambios que esto conlleva en el script de creación de la BD.

2021-02-01 16:32 UTC, infacorchado commented
- En las vistas, al hacer la validación de datos lo estáis validando pero sacáis un mensaje por consola... esto no tiene mucho sentido porque el usuario de esta forma no se entera que está introduciendo algo mal. Sacad un mensaje por ventana o mas fácil, poner un control que acepte valores numéricos. 
- controlar bien los errores, por ejemplo si pongo algo en cantidad y le doy al botón seleccionar sin seleccionar un producto da un error.  (en facturas , imagino que en el resto de pantalla pasará igual)
- Debería existir la opción de eliminar un producto después de seleccionarlo.

2021-02-02 13:07 UTC, infacorchado approved these changes

2021-02-02 21:48 UTC, Jose-Elorrieta commented
Está correctamente hecho el paso a 3FN y los cambios que conlleva esto en el diseño físico. Sin embargo, al revisar de nuevo vuestro script, me he dado cuenta de que no habéis incorporado en el script (sí en el esquema relacional) el reflejo de la relación entre Operación y Local. Dado que una operación se realiza en un único local, hay que colocar (como bien habéis indicado en el esquema relacional) en la tabla Operación una clave ajena para indicar el local en el que se lleva a cabo la operación. 
Habéis creado una nueva tabla con 2 claves foráneas, lo que sería correcto si una operación se pudiese llevar a cabo en varios locales, pero no es el caso. Corregid esto en el script de creación de la BD, por favor.

2021-02-03 07:54 UTC, Jose-Elorrieta approved these changes
De acuerdo. La parte de BD correspondiente al sprint 1 es correcta.

2021-02-03 14:33 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/Controlador.java
> +	private static Modelo modelo;
Porque es estático?

2021-02-03 14:35 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +	public void accionadoBotonCrearTicket() {
Elimina esta metodo

2021-02-03 14:36 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Actividad.java
> +	public Actividad(int numTransaccion, Date fecha, String local)
El constructor lo ponemos al principio

2021-02-03 14:38 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Conexion.java
> +	private static final String URL="jdbc:mysql://localhost:33060/"+NOMBREBD+"?useUnicode=true&use"
Si vas a meter un string dentro de otro string estático, lo que debes hacer es utilizar un placeholder

2021-02-03 14:39 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Factura.java
> +	public Factura(int numTransaccion, Date fecha, String local, String nif, String nombre, String apellido) {
el constructor arriba

2021-02-03 14:41 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Local.java
> +		Producto prod = new Producto(nombre);
Donde usas prod?

2021-02-03 14:42 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Modelo.java
> +	//private Conexion conexion = new Conexion();
quita eso

2021-02-03 14:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Modelo.java
>  public class Modelo {
En el modelo solo deberíamos de añadir las instancias al resto de las clases que componen el paquete modelo. De tal forma que el controlador pueda acceder a ellas. Lo que tenemos que hacer es convertirlo en un cajon de sastre en el que metemos todo aquello que no sabemos donde meterlo. Corregid esto por favor.

2021-02-03 14:50 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Vista/PanelFacturas.java
> +					annadidos.remove(pos);
Esto viendo que estás cogiendo la costumbre de meter más lógica que la necesaria en las vistas. Esto a la larga te va acarrear muchos problemas. Porque, por un lado, las vistas no podemos testearlas mediante teses unitarios y esto acarrea que sea más difícil identificar los bugs. Por otra parte, si quieres testear todos escenarios posibles en las vistas tendrías que hacer un montón de test funcionales, lo cual lastraría los despliegues del código (aún no sabemos hacer test funcionales). Así que, por favor que las vistas hagan lo mínimo posible y cualquier transformación o tratamiento de datos que sea procesado por el controlador.

2021-02-03 14:51 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Vista/PanelPedidos.java
> +					}
+1

2021-02-03 14:51 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Vista/PanelPedidos.java
> +			}
+1

2021-02-03 14:52 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Vista/PanelTickets.java
> +			}
+1

2021-02-03 14:52 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Vista/PanelTickets.java
> +		};
+1

2021-02-03 14:52 UTC, infabeti commented on CineElorrietaMVC/src/test/java/TestControlador/TestControladorPanelPedidos.java
> +	}*/
borra esto

2021-02-03 14:53 UTC, infabeti requested changes
Os he puesto unos comentarios. Cuando lo arregléis os miro los test.

2021-02-03 17:03 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Local.java
> +		Producto prod = new Producto(nombre);
Se utiliza justo debajo para crear un objeto de tipo ProductoTienda y poder buscarlo en la lista

2021-02-03 18:18 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/Controlador.java
> +	private static Modelo modelo;
Al final del código para el controlador hay dos métodos estáticos

2021-02-03 18:19 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Conexion.java
> +	private static final String URL="jdbc:mysql://localhost:33060/"+NOMBREBD+"?useUnicode=true&use"
¿Sería correcto dejarlos en final únicamente? Son constantes y no se utilizan en ningún método estático

2021-02-05 19:53 UTC, Jose-Elorrieta reviewed
En cuanto al diagrama E-R, para los platos es necesario saber si un plato es 1º, 2º o postre. También para los platos se requiere saber si es vegetariano, vegano o nada de esto. En principio, el enunciado solo pide esto (si es vegetariano o vegano) para los platos, pero no me parece mal que se indique también para todo producto que se vende en los locales.
En el diagrama E-R quedamos que solo relacionaríamos Empleado o Usuario con un local para simplificar. Esto no está reflejado en el diagrama E-R.
En el paso a tablas lo veo todo correcto. 
En el script veo los siguientes fallos:- En Actividad el atributo NIF que indica el local en el que se realiza la transaccióndebe ser obligatorio.- El atributo FeCad en Alimento no creo que deba ser obligatorio pues hay productos y/o ingredientes sin fecha de caducidad.- La clave ajena CodigoAlimento en LineaProducto debe apuntar a Producto.- Para los atributos booleanos, si queremos que si no se les da valor tomen valor false, hay que poner este valor como valor por defecto.
¡MUY BUEN TRABAJO!

2021-02-08 07:26 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/Controlador.java
> +	private static Modelo modelo;
Pues ponlos dinamicos

2021-02-08 07:28 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		int cantidad = Integer.parseInt(eliminar.substring(0, punt));
Probablemente puedas hacer un metodo con esto en el modelo

2021-02-08 07:28 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +		punt++;
Puedes reutilizar el metodo que te he dicho que hagas

2021-02-08 07:29 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +		punt++;
+1

2021-02-08 07:30 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Local.java
> +		Producto prod = new Producto(nombre);
OK

2021-02-08 07:30 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/Modelo.java
>  public class Modelo {
Sigue sin estar solucionado

2021-02-08 07:34 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		int cantidad = Integer.parseInt(eliminar.substring(0, punt));
Corregido

2021-02-08 07:34 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +		punt++;
Corregido

2021-02-08 07:34 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +		punt++;
Corregido

2021-02-08 07:39 UTC, infabeti requested changes
Cambiad esto

2021-02-09 10:25 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Modelo/Modelo.java
>  public class Modelo {
Solucionado

2021-02-09 10:25 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/Controlador.java
> +	private static Modelo modelo;
Eliminado el método

2021-02-10 06:29 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/Controlador.java
> +	private static Modelo modelo;
Sigue siendo static

2021-02-10 06:34 UTC, infabeti commented on CineElorrietaMVC/src/test/java/TestControlador/TestControladorPanelPedidos.java
> +	}*/
Esto?

2021-02-10 06:34 UTC, infabeti commented on CineElorrietaMVC/src/test/java/TestControlador/TestControladorPanelPedidos.java
> +	public void TestaccionadoBotonAnnadirProducto()
Esto no está haciendo nada

2021-02-10 06:35 UTC, infabeti commented on CineElorrietaMVC/src/test/java/TestModelo/TestActividades.java
> +		boolean res = p1.esDomicilio();
Solo hacemos un assert por test. Si quieres verficar el true y el false teneis que hacer varios test

2021-02-10 06:36 UTC, infabeti commented on CineElorrietaMVC/src/test/java/TestModelo/TestActividades.java
> +	public void testEquals() {
+1

2021-02-10 06:38 UTC, infabeti requested changes
Los test están mal, si queréis podemos mergear sin hacer los test y esa parte no se evalúa.

2021-02-10 07:21 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/main/java/Controlador/Controlador.java
> +	private static Modelo modelo;
Arreglado, ahora lo subo

2021-02-10 07:21 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/test/java/TestControlador/TestControladorPanelPedidos.java
> +	}*/
Eliminado

2021-02-10 07:22 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/test/java/TestControlador/TestControladorPanelPedidos.java
> +	public void TestaccionadoBotonAnnadirProducto()
Eliminado

2021-02-10 07:24 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/test/java/TestModelo/TestActividades.java
> +		boolean res = p1.esDomicilio();
De acuerdo, el TestActividades está corregido

2021-02-10 07:24 UTC, Unai-GarciaGi commented on CineElorrietaMVC/src/test/java/TestModelo/TestActividades.java
> +	public void testEquals() {
Corregido también

2021-02-10 07:38 UTC, Unai-GarciaGi commented
Estamos de acuerdo con mergear sin los tests, aunque he podido arreglar lo de un assert por test en Actividades

2021-02-10 07:52 UTC, merged