Sprint2 - Pull request Equipo1
infabeti/Equipo1-Aitor-Unai pull request #3
Opened 2021-03-09 11:53 UTC by AitorCalderonLo

2021-03-09 11:55 UTC, AitorCalderonLo commented
Hemos reducido todo lo que hemos podido los controladores, no vemos la manera de reducirlo mas.

2021-03-09 18:53 UTC, Jose-Elorrieta approved these changes
El diseño de la BD es correcto

2021-03-11 15:36 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		return modelo.getUser().getNifLocal();
this.

2021-03-11 15:37 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		modelo.getListaTemporal().limpiarLista();
+1

2021-03-11 15:38 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		return modelo.getListaTemporal().devolverPosProductoString(nombreProducto);
this

2021-03-11 15:42 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +	public String[] accionadoBotonAnnadirProducto(String producto, String cantidad) {
Este metodo no existe en ControladorPanelFacturas?

2021-03-11 15:42 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +	public String[] cambiarCantidadProductos(String nombreProductoAnadido, int cantidadAnadir, String nombreProducto) {
+1

2021-03-11 15:42 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +	public void insertarActividad(int transaccion, String fecha, double totalOperacion, String nif, String domicilio,
No haceis algo parecido en ControladorPanelFacturas?

2021-03-11 15:43 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelRegistro.java
> +	public String comprobarCamposRegistro(String nombre, String apellido, String nif, String dni, String password) {
Yo, un validador lo pondría en el modelo.

2021-03-11 15:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +	public String[] accionadoBotonAnnadirProducto(String producto, String cantidad) {
Parece ser que repetís los mismos metodos una y otra vez. Crear un llamada a un metodo generico que creeis en el modelo.

2021-03-11 15:44 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelTickets.java
> +	public String[] cambiarCantidadProductos(String nombreProductoAnadido, int cantidadAnadir, String nombreProducto) {
...

2021-03-11 15:47 UTC, infabeti commented on CineElorrietaMVC/src/main/java/Modelo/ConsultasComprobaciones.java
> +public class ConsultasComprobaciones {
Son iguales los tres metodos. Podeis hacerlo mejor y crear un metodo generico con todo el codigo repetido. Y, pasarle por parametro el nombre del statement

2021-03-11 15:49 UTC, infabeti requested changes
Os he puesto unos comentarios. Pero, va mejorando. Cuando lo arregleis os sigo mirando.

2021-03-12 10:40 UTC, AitorCalderonLo commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		return modelo.getUser().getNifLocal();
Corregido.

2021-03-12 10:40 UTC, AitorCalderonLo commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		modelo.getListaTemporal().limpiarLista();
Corregido.

2021-03-12 10:41 UTC, AitorCalderonLo commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelFacturas.java
> +		return modelo.getListaTemporal().devolverPosProductoString(nombreProducto);
Corregido.

2021-03-12 10:50 UTC, AitorCalderonLo commented on CineElorrietaMVC/src/main/java/Modelo/ConsultasComprobaciones.java
> +public class ConsultasComprobaciones {
Genial, solucionado.

2021-03-12 10:59 UTC, AitorCalderonLo commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelPedidos.java
> +	public void insertarActividad(int transaccion, String fecha, double totalOperacion, String nif, String domicilio,
Si, tenemos el mismo método en los controladores de pedido, factura, ticket ya que dependiendo de el panel desde el que nos comuniquemos tenemos que llamar a unos u otros métodos del modelo.

2021-03-12 11:16 UTC, AitorCalderonLo commented on CineElorrietaMVC/src/main/java/Controlador/ControladorPanelRegistro.java
> +	public String comprobarCamposRegistro(String nombre, String apellido, String nif, String dni, String password) {
Solucionado, hemos creado una clase registro en el modelo.

2021-03-12 13:18 UTC, AitorCalderonLo commented
Hemos realizado los cambios

2021-03-13 14:57 UTC, infabeti approved these changes

2021-03-13 14:57 UTC, merged